name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  document:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Retrieve style files
        run: |
          git submodule add https://github.com/jothepro/doxygen-awesome-css.git
          cd doxygen-awesome-css
          git checkout v2.4.2

      - name: Copy style files
        run: |
          mkdir -p docs/theme
          cp doxygen-awesome-css/doxygen-awesome.css docs/theme/
          cp doxygen-awesome-css/doxygen-awesome-sidebar-only.css docs/theme/

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
