name: CD

run-name: "CD: ${{ github.event.workflow_run.head_commit.message }}"

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Attempt to download .docs-venv artifact
        id: download-docs-venv
        uses: actions/download-artifact@v4
        with:
          name: build-cache
          path: ./.docs-venv
        continue-on-error: true

      - name: Check if the artifact was successfully downloaded
        id: check-for-venv
        run: |
          if [ -d ".docs-venv" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build documentation
        run: sudo make docs

      - name: "Debug: List files "
        run: |
          sudo apt-get install -y tree
          tree ../../..

      - name: Upload artifact
        if: steps.check-for-venv.outputs.exists == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: build-cache
          path: ./.docs-venv
          retention-days: 2

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
