name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  document:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Retrieve style files from doxygen-awesome-css repository
        run: |
          git clone https://github.com/jothepro/doxygen-awesome-css.git

      - name: Copy extension and style files to documentation folder
        run: |
          mkdir -p docs/html/theme
          mkdir -p docs/html/extensions
          cp doxygen-awesome-css/doxygen-awesome.css docs/html/theme/
          cp doxygen-awesome-css/doxygen-awesome-sidebar-only.css docs/html/theme/
          cp doxygen-awesome-css/doxygen-awesome-sidebar-only-darkmode-toggle.css docs/html/theme/
          cp doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js docs/html/extensions/
          cp doxygen-awesome-css/doxygen-awesome-paragraph-link.js docs/html/extensions/
          cp doxygen-awesome-css/doxygen-awesome-interactive-toc.js docs/html/extensions/

      - name: Remove style files from repository
        run: |
          rm -rf doxygen-awesome-css

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
