name: Format

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  formatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          find src -name "*.c" ! -name "*.bpf.c" | \
            xargs clang-format -i
